import { VueShowdown } from "vue-showdown";
import { VAceEditor } from "vue3-ace-editor";
import { ColorPicker } from "vue3-colorpicker";

import draggable from "vuedraggable";
import VueMarkdown from "vue-markdown-render";
import VueCodeHighlight from "vue-code-highlight";
import VueDatePicker from '@vuepic/vue-datepicker';

import "vue3-colorpicker/style.css";
import '@vuepic/vue-datepicker/dist/main.css';

import EC_Auth from "@/components/App/EC_Auth.vue";
import EC_Debug from "@/components/App/EC_Debug.vue";
import EC_Alert from "@/components/Exam/EC_Alert.vue";
import EC_Popups from "@/components/App/EC_Popups.vue";
import EC_Header from "@/components/App/EC_Header.vue";
import EC_Users from "@/components/Admin/EC_Users.vue";
import EC_Window from "@/components/Exam/EC_Window.vue";
import EC_Title from "@/components/Global/EC_Title.vue";
import EC_Input from "@/components/Global/EC_Input.vue";
import EC_Editor from "@/components/Exam/EC_Editor.vue";
import EC_Tooltip from "@/components/App/EC_Tooltip.vue";
import EC_SideBar from "@/components/Exam/EC_SideBar.vue";
import EC_Button from "@/components/Global/EC_Button.vue";
import EC_Log from "@/components/Exam/Windows/EC_Log.vue";
import EC_AllExams from "@/components/Admin/EC_AllExams.vue";
import EC_CheckBox from "@/components/Global/EC_CheckBox.vue";
import EC_Subtitle from "@/components/Global/EC_Subtitle.vue";
import EC_Dropdown from "@/components/Global/EC_Dropdown.vue";
import EC_TextArea from "@/components/Global/EC_TextArea.vue";
import EC_AdminExam from "@/components/Admin/EC_AdminExam.vue";
import EC_PopupCard from "@/components/Global/EC_PopupCard.vue";
import EC_AdminPanel from "@/components/Admin/EC_AdminPanel.vue";
import EC_InputLabel from "@/components/Global/EC_InputLabel.vue";
import EC_Preview from "@/components/Exam/Windows/EC_Preview.vue";
import EC_EditExam from "@/components/Admin/Exam/EC_EditExam.vue";
import EC_UserData from "@/components/Admin/Items/EC_UserData.vue";
import EC_ExamData from "@/components/Admin/Items/EC_ExamData.vue";
import EC_ButtonGoogle from "@/components/App/EC_ButtonGoogle.vue";
import EC_ProgressBar from "@/components/Global/EC_ProgressBar.vue";
import EC_WindowTitles from "@/components/Exam/EC_WindowTitles.vue";
import EC_NumberInput from "@/components/Global/EC_NumberInput.vue";
import EC_Markdown from "@/components/Exam/Windows/EC_Markdown.vue";
import EC_JS_Editor from "@/components/Exam/Windows/EC_JS_Editor.vue";
import EC_DarkModeToggle from "@/components/App/EC_DarkModeToggle.vue";
import EC_WindowsSettings from "@/components/Exam/EC_WindowsSettings.vue";
import EC_HTML_Editor from "@/components/Exam/Windows/EC_HTML_Editor.vue";
import EC_StartExamDialog from "@/components/Exam/EC_StartExamDialog.vue";
import EC_UserSolution from "@/components/Admin/Items/EC_UserSolution.vue";
import EC_SideBarSolutions from "@/components/Exam/EC_SideBarSolutions.vue";
import EC_ExamSolutions from "@/components/Admin/Exam/EC_ExamSolutions.vue";
import EC_ScriptVisibility from "@/components/Admin/EC_ScriptVisibility.vue";
import EC_EditExamStore from "@/components/App/Debugging/EC_EditExamStore.vue";
import EC_EditUserStore from "@/components/App/Debugging/EC_EditUserStore.vue";
import EC_EditFileStore from "@/components/App/Debugging/EC_EditFileStore.vue";
import EC_EditAdminStore from "@/components/App/Debugging/EC_EditAdminStore.vue";
import EC_EditGlobalStore from "@/components/App/Debugging/EC_EditGlobalStore.vue";
import EC_EditTestingStore from "@/components/App/Debugging/EC_EditTestingStore.vue";
import EC_VisibilityAuthChange from "@/components/App/EC_VisibilityAuthChange.vue";
import EC_DebugSelectButton from "@/components/App/Debugging/EC_DebugSelectButton.vue";

function setUpComponents(app) {
	app.component("draggable", draggable);
	app.component("VAceEditor", VAceEditor);
	app.component("VueShowdown", VueShowdown);
	app.component("VueMarkdown", VueMarkdown);
	app.component("ColorPicker", ColorPicker);
	app.component('VueDatePicker', VueDatePicker);
	
	app.use(VueCodeHighlight);

	app.component("EC_Log", EC_Log);
	app.component("EC_Auth", EC_Auth);
	app.component("EC_Debug", EC_Debug);
	app.component("EC_Alert", EC_Alert);
	app.component("EC_Title", EC_Title);
	app.component("EC_Input", EC_Input);
	app.component("EC_Users", EC_Users);
	app.component("EC_Editor", EC_Editor);
	app.component("EC_Popups", EC_Popups);
	app.component("EC_Button", EC_Button);
	app.component("EC_Window", EC_Window);
	app.component("EC_Header", EC_Header);
	app.component("EC_SideBar", EC_SideBar);
	app.component("EC_Preview", EC_Preview);
	app.component("EC_Tooltip", EC_Tooltip);
	app.component("EC_UserData", EC_UserData);
	app.component("EC_ExamData", EC_ExamData);
	app.component("EC_EditExam", EC_EditExam);
	app.component("EC_CheckBox", EC_CheckBox);
	app.component("EC_Subtitle", EC_Subtitle);
	app.component("EC_Dropdown", EC_Dropdown);
	app.component("EC_TextArea", EC_TextArea);
	app.component("EC_Markdown", EC_Markdown);
	app.component("EC_AllExams", EC_AllExams);
	app.component("EC_AdminExam", EC_AdminExam);
	app.component("EC_JS_Editor", EC_JS_Editor);
	app.component("EC_PopupCard", EC_PopupCard);
	app.component("EC_AdminPanel", EC_AdminPanel);
	app.component("EC_InputLabel", EC_InputLabel);
	app.component("EC_ProgressBar", EC_ProgressBar);
	app.component("EC_NumberInput", EC_NumberInput);
	app.component("EC_HTML_Editor", EC_HTML_Editor);
	app.component("EC_WindowTitles", EC_WindowTitles);
	app.component("EC_ButtonGoogle", EC_ButtonGoogle);
	app.component("EC_UserSolution", EC_UserSolution);
	app.component("EC_ExamSolutions", EC_ExamSolutions);
	app.component("EC_EditExamStore", EC_EditExamStore);
	app.component("EC_EditUserStore", EC_EditUserStore);
	app.component("EC_EditFileStore", EC_EditFileStore);
	app.component("EC_EditAdminStore", EC_EditAdminStore);
	app.component("EC_DarkModeToggle", EC_DarkModeToggle);
	app.component("EC_WindowsSettings", EC_WindowsSettings);
	app.component("EC_EditGlobalStore", EC_EditGlobalStore);
	app.component("EC_StartExamDialog", EC_StartExamDialog);
	app.component("EC_EditTestingStore", EC_EditTestingStore);
	app.component("EC_ScriptVisibility", EC_ScriptVisibility);
	app.component("EC_SideBarSolutions", EC_SideBarSolutions);
	app.component("EC_DebugSelectButton", EC_DebugSelectButton);
	app.component("EC_VisibilityAuthChange", EC_VisibilityAuthChange);
}

export { setUpComponents };
